[package]
name = "S1342-number-of-steps-to-reduce-a-number-to-zero"
version = "0.1.0"
authors = ["Xargin <cao1988228@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
